root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main serve --http=0.0.0.0:8090"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "pb_data", "migrations"]
delay = 1000
kill_delay = "0.5s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = true 