services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Added HTTPS port
      - "25:25"    # SMTP
      - "143:143"  # IMAP
      - "465:465"  # SMTPS
      - "587:587"  # SMTP Submission
      - "993:993"  # IMAPS
    environment:
      - MAIL_SERVICE=smtp4dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/stream.dev.conf:/etc/nginx/stream.conf
      - ./nginx/ssl:/etc/nginx/ssl  # Added SSL certificates
    depends_on:
      - frontend
      - pocketbase
      - smtp4dev
    networks:
      - web

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - web

  pocketbase:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - backend_go_mod_cache:/go/pkg/mod
      - ../backend/pb_data:/app/tmp/pb_data
      - ../backend/migrations:/app/tmp/migrations
      - ../backend:/app
    environment:
      - APP_ENV=development
    networks:
      - web
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://api.localhost/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  smtp4dev:
    image: rnwood/smtp4dev:latest
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__BasePath=/
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__NumberOfMessagesToKeep=100
      - ServerOptions__NumberOfSessionsToKeep=100
    networks:
      - web

volumes:
  smtp4dev-data:
  frontend_node_modules:
  backend_go_mod_cache:

networks:
  web:
    driver: bridge 