services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "25:25"   # SMTP
      - "465:465" # SMTPS
      - "587:587" # SMTP Submission
      - "993:993" # IMAPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/stream.prod.conf:/etc/nginx/stream.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - pocketbase
      - stalwart
    networks:
      - web

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_POCKETBASE_URL=https://api.bemte.li
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POCKETBASE_URL=https://api.bemte.li
    networks:
      - web

  pocketbase:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/pb_data:/app/pb_data
    env_file:
      - .env.production
    networks:
      - web
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  stalwart:
    image: stalwartlabs/mail-server:latest
    container_name: stalwart-mail
    restart: unless-stopped
    volumes:
      - /opt/stalwart-mail:/opt/stalwart-mail
      - ./certbot/conf:/etc/letsencrypt:ro  # Give access to certificates
      - /etc/localtime:/etc/localtime:ro    # Ensure correct timezone
    environment:
      - STALWART_PATH=/opt/stalwart-mail
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - web

networks:
  web:
    driver: bridge 